# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fintrack
spring.datasource.username=root
spring.datasource.password=2405@Falak

# API Path
server.servlet.context-path=/api

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Config File
spring.profiles.active=dev

# Email Configuration
spring.mail.host=${SMTP_Host}
spring.mail.port=${SMTP_Port}
spring.mail.username=${SMTP_Username}
spring.mail.password=${SMTP_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${SMTP_Email}

# JWT Configuration
jwt.secret=${JWT_Secret}
jwt.expiration=${JWT_Expire}
